import {
  User,
  Conversation,
  ChatMessage,
  PersonItem,
  LocationItem,
  ServiceItem,
  NavigationRoute,
  AdminMetric,
  VerificationItem,
  Announcement,
  ProcedureItem,
} from '../types';

export const mockCurrentUser: User = {
  id: 'usr_nex_01',
  name: 'Alex Rivera',
  email: 'alex.rivera@nexora.edu',
  role: 'student',
  department: 'Computer Science & AI',
  community: 'Nexora Institute of Technology',
  year: 'Year 3',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  preferences: {
    language: 'English (US)',
    voiceModel: 'ElevenLabs Nova (Neural HD)',
    voiceEnabled: true,
    notifications: {
      email: true,
      push: true,
      sound: false,
    },
    appearance: 'dark-glass',
  },
  createdAt: '2024-08-15T10:00:00Z',
};

export const mockConversations: Conversation[] = [
  {
    id: 'conv_1',
    title: 'ID Card Replacement Procedure',
    lastMessage: 'Here is the step-by-step procedure and required documents for your student ID replacement.',
    updatedAt: '2026-09-06T14:32:00Z',
    createdAt: '2026-09-06T14:30:00Z',
    tags: ['Procedure', 'Student Services', 'ID'],
  },
  {
    id: 'conv_2',
    title: 'Quantum Computing Lab Location',
    lastMessage: 'The lab is situated on Floor 3 of the Silver Jubilee Tower (Room SJT-312).',
    updatedAt: '2026-09-05T18:15:00Z',
    createdAt: '2026-09-05T18:10:00Z',
    tags: ['Location', 'Labs', 'Navigation'],
  },
  {
    id: 'conv_3',
    title: 'Transcript & Bonafide Certificate',
    lastMessage: 'You can submit the digital request through Academic Registry portal or visit Room MB-104.',
    updatedAt: '2026-09-03T11:45:00Z',
    createdAt: '2026-09-03T11:40:00Z',
    tags: ['Academic', 'Certificates'],
  },
  {
    id: 'conv_4',
    title: 'Hostel Night-Out Permission Protocol',
    lastMessage: 'Parental verification via OTP is mandatory prior to 8:30 PM.',
    updatedAt: '2026-08-29T21:00:00Z',
    createdAt: '2026-08-29T20:50:00Z',
    tags: ['Hostel', 'Policy'],
  },
];

export const mockIdCardProcedure: ProcedureItem = {
  id: 'proc_id_01',
  title: 'ID Card Replacement',
  category: 'Student Services & Security',
  responsibleOffice: 'Student Services Center',
  location: 'Silver Jubilee Tower (SJT) — Ground Floor — Room G12',
  hours: '9:00 AM – 4:30 PM (Mon – Fri)',
  requiredDocuments: [
    'Original Government ID (Passport / Driver License / Aadhaar)',
    'Campus Police Incident Log or Lost Affidavit receipt',
    'Proof of active term enrollment / fee clearance receipt',
    'Passport size photograph (or capture at desk)',
  ],
  steps: [
    'Fill the digital lost property declaration at the Campus Security desk.',
    'Visit Student Services (SJT-G12) during working hours.',
    'Present the required documents at Counter 3 for biometrics verification.',
    'Collect your smart RFID-enabled ID card within 15 minutes of fee settlement ($15).',
  ],
  contactEmail: 'studentservices@nexora.edu',
};

export const mockProcedures: ProcedureItem[] = [mockIdCardProcedure];

export const mockInitialMessages: Record<string, ChatMessage[]> = {
  conv_1: [
    {
      id: 'msg_1_1',
      conversationId: 'conv_1',
      role: 'user',
      content: 'I lost my student ID card today morning. What should I do and where do I go?',
      timestamp: '2026-09-06T14:30:15Z',
    },
    {
      id: 'msg_1_2',
      conversationId: 'conv_1',
      role: 'assistant',
      content: 'I have retrieved the verified community protocol for Student ID Replacement from the Student Services Registry. You can complete this today before 4:30 PM at the Silver Jubilee Tower.',
      timestamp: '2026-09-06T14:31:02Z',
      structuredData: {
        type: 'procedure',
        procedure: mockIdCardProcedure,
        location: {
          id: 'loc_sjt_g12',
          name: 'Student Services Center',
          building: 'Silver Jubilee Tower (SJT)',
          floor: 'Ground Floor',
          room: 'G12',
          category: 'Administration',
          operatingHours: '9:00 AM – 4:30 PM',
          accessible: true,
          description: 'Primary helpdesk for student cards, admissions, document stamps, and verification.',
        },
      },
      sources: [
        {
          id: 'src_reg_01',
          title: 'Student Handbook 2026 — Section 4.2: Identification Credentials',
          sourceDocument: 'Campus Registry Verified Repository',
          pageOrSection: 'Page 34, Subsection B',
          confidenceScore: 0.98,
          verifiedAt: '2026-08-01',
        },
      ],
    },
  ],
  conv_2: [
    {
      id: 'msg_2_1',
      conversationId: 'conv_2',
      role: 'user',
      content: 'Where is the Quantum Computing Lab and who is the faculty in charge?',
      timestamp: '2026-09-05T18:10:00Z',
    },
    {
      id: 'msg_2_2',
      conversationId: 'conv_2',
      role: 'assistant',
      content: 'The Advanced Quantum Information Lab is located in the Silver Jubilee Tower. Here are the exact location coordinates, navigation path, and in-charge faculty details.',
      timestamp: '2026-09-05T18:11:00Z',
      structuredData: {
        type: 'location',
        location: {
          id: 'loc_sjt_312',
          name: 'Quantum Information & Computing Lab',
          building: 'Silver Jubilee Tower (SJT)',
          floor: '3rd Floor',
          room: 'Room 312',
          category: 'Research & Labs',
          operatingHours: '8:00 AM – 8:00 PM',
          accessible: true,
          description: 'Equipped with cryogenic dilution refrigerator simulations and IBM Quantum Cloud nodes.',
        },
        person: {
          id: 'per_01',
          name: 'Dr. Elena Rostova',
          role: 'Professor & Head of Quantum Computing',
          department: 'Department of Computer Science',
          office: 'Room SJT-318',
          building: 'Silver Jubilee Tower',
          email: 'elena.rostova@nexora.edu',
          phone: '+1 (555) 234-8901',
          availability: 'Available',
          officeHours: 'Tues & Thurs 2:00 PM – 4:00 PM',
          avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        },
      },
      sources: [
        {
          id: 'src_lab_02',
          title: 'Campus Laboratory Directory & Faculty Guide 2026',
          sourceDocument: 'School of Computing Sciences',
          pageOrSection: 'Directory Entry #412',
          confidenceScore: 0.99,
          verifiedAt: '2026-08-15',
        },
      ],
    },
  ],
};

export const mockPeople: PersonItem[] = [
  {
    id: 'per_01',
    name: 'Dr. Elena Rostova',
    role: 'Faculty - Lead Scientist',
    department: 'Computer Science & AI',
    office: 'Room SJT-318',
    building: 'Silver Jubilee Tower',
    email: 'elena.rostova@nexora.edu',
    phone: '+1 (555) 019-2831',
    availability: 'Available',
    officeHours: 'Tue, Thu 2:00 PM - 4:00 PM',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'per_02',
    name: 'Prof. Marcus Vance',
    role: 'Dean of Academic Affairs',
    department: 'Academic Administration',
    office: 'Main Building 204',
    building: 'Main Administrative Center',
    email: 'marcus.vance@nexora.edu',
    phone: '+1 (555) 019-4412',
    availability: 'Busy',
    officeHours: 'Wed 10:00 AM - 12:00 PM by appointment',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'per_03',
    name: 'Sarah Chen, M.S.',
    role: 'Senior Systems Administrator',
    department: 'IT Infrastructure',
    office: 'Technology Center T-102',
    building: 'Center for Applied Technology',
    email: 'sarah.chen@nexora.edu',
    phone: '+1 (555) 019-7819',
    availability: 'Available',
    officeHours: 'Mon-Fri 9:00 AM - 5:00 PM',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'per_04',
    name: 'Dr. Tariq Al-Mansoor',
    role: 'Associate Professor',
    department: 'Robotics & Mechatronics',
    office: 'SJT-508',
    building: 'Silver Jubilee Tower',
    email: 'tariq.mansoor@nexora.edu',
    phone: '+1 (555) 019-9021',
    availability: 'In Class',
    officeHours: 'Mon, Wed 1:00 PM - 3:00 PM',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'per_05',
    name: 'Clara Oswald',
    role: 'Lead Student Wellness Counselor',
    department: 'Health & Wellness Center',
    office: 'Health Pavilion 104',
    building: 'Campus Health & Recreation',
    email: 'clara.oswald@nexora.edu',
    phone: '+1 (555) 019-3321',
    availability: 'Office Hours Only',
    officeHours: 'Daily 11:00 AM - 3:00 PM',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'per_06',
    name: 'David K. O’Connor',
    role: 'Campus Facilities Manager',
    department: 'Facilities & Campus Operations',
    office: 'Ops Hub O-11',
    building: 'Operations Facility',
    email: 'david.oconnor@nexora.edu',
    phone: '+1 (555) 019-6129',
    availability: 'Available',
    officeHours: 'Mon-Fri 8:00 AM - 4:00 PM',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockLocations: LocationItem[] = [
  {
    id: 'loc_sjt_g12',
    name: 'Student Services Center',
    building: 'Silver Jubilee Tower (SJT)',
    floor: 'Ground Floor',
    room: 'Room G12',
    category: 'Administration',
    operatingHours: '9:00 AM – 4:30 PM (Mon-Fri)',
    accessible: true,
    description: 'Central hub for enrollment documents, ID card issuance, bursar inquiries, and verifications.',
  },
  {
    id: 'loc_lib_main',
    name: 'Nexora Central Library',
    building: 'Library & Information Commons',
    floor: 'Levels 1 - 4',
    room: 'Main Wing',
    category: 'Study & Research',
    operatingHours: '24 Hours (Active Term)',
    accessible: true,
    description: 'Over 250,000 volumes, silent study zones, multimedia studios, and high-speed Wi-Fi carrels.',
  },
  {
    id: 'loc_sjt_312',
    name: 'Quantum Information Lab',
    building: 'Silver Jubilee Tower (SJT)',
    floor: '3rd Floor',
    room: 'Room 312',
    category: 'Labs & Research',
    operatingHours: '8:00 AM – 8:00 PM',
    accessible: true,
    description: 'Specialized lab for quantum algorithms, simulator clusters, and cryptography testbeds.',
  },
  {
    id: 'loc_cat_102',
    name: 'IT Helpdesk & Device Support',
    building: 'Center for Applied Technology',
    floor: '1st Floor',
    room: 'Room T-102',
    category: 'IT Services',
    operatingHours: '8:30 AM – 6:00 PM',
    accessible: true,
    description: 'Hardware diagnostics, campus network access token generation, and software licensing desk.',
  },
  {
    id: 'loc_hwc_104',
    name: 'Campus Medical & Wellness Pavilion',
    building: 'Health & Recreation Center',
    floor: 'Ground Floor',
    room: 'Room H-104',
    category: 'Health & Emergency',
    operatingHours: '24/7 Triage & Outpatient',
    accessible: true,
    description: 'Immediate medical first response, nursing station, pharmacy dispensing, and counseling suites.',
  },
  {
    id: 'loc_aud_main',
    name: 'Sirius Grand Auditorium',
    building: 'Sirius Cultural Center',
    floor: 'Ground & Balcony',
    room: 'Hall A',
    category: 'Auditorium',
    operatingHours: 'Event Dependent',
    accessible: true,
    description: '1,800-seat state-of-the-art auditorium with acoustic treatment and simultaneous translation gear.',
  },
];

export const mockServices: ServiceItem[] = [
  {
    id: 'srv_01',
    name: 'Digital Academic Registry & Transcripts',
    description: 'Request official transcripts, grade verification letters, course syllabus attestations, and diploma re-issuance.',
    category: 'Academic',
    department: 'Registrar Office',
    location: 'Main Administrative Center — Room MB-104',
    hours: '9:30 AM – 4:00 PM (Mon – Fri)',
    contactEmail: 'registry@nexora.edu',
  },
  {
    id: 'srv_02',
    name: 'Emergency Medical & Ambulance Dispatch',
    description: 'On-campus 24/7 rapid medical emergency triage, EMT paramedic ambulance dispatch, and urgent care.',
    category: 'Health & Emergency',
    department: 'University Medical Center',
    location: 'Health Pavilion — Ground Floor — Triage Bay',
    hours: '24 Hours / 7 Days a Week',
    contactEmail: 'emergency-health@nexora.edu',
    isUrgent: true,
  },
  {
    id: 'srv_03',
    name: 'IT Network, VPN & Single Sign-On Support',
    description: 'Resolution of multi-factor authentication issues, eduroam Wi-Fi configuration, software distribution, and hardware repairs.',
    category: 'IT & Labs',
    department: 'Information Technology Services',
    location: 'Center for Applied Technology — Room T-102',
    hours: '8:30 AM – 7:00 PM (Mon – Sat)',
    contactEmail: 'itsupport@nexora.edu',
  },
  {
    id: 'srv_04',
    name: 'Student Career & Internship Placement Cell',
    description: 'Resume review, mock technical interviews, campus placement drives, and employer networking summits.',
    category: 'Student Services',
    department: 'Corporate Relations & Career Center',
    location: 'Silver Jubilee Tower — 2nd Floor — Room SJT-201',
    hours: '9:00 AM – 5:00 PM (Mon – Fri)',
    contactEmail: 'careers@nexora.edu',
  },
  {
    id: 'srv_05',
    name: 'Campus Facilities & Lost Property Office',
    description: 'Central collection for found items (keys, devices, IDs), facility repair dispatches, and locker requests.',
    category: 'Facilities',
    department: 'Campus Security & Operations',
    location: 'Operations Hub — Room O-11',
    hours: '8:00 AM – 8:00 PM (Daily)',
    contactEmail: 'facilities@nexora.edu',
  },
  {
    id: 'srv_06',
    name: 'Student Wellness & Mental Health Counseling',
    description: 'Confidential 1-on-1 counseling, mindfulness workshops, stress management clinics, and cognitive support.',
    category: 'Student Services',
    department: 'Mental Wellness Alliance',
    location: 'Health & Recreation Center — Room H-205',
    hours: '10:00 AM – 6:00 PM (By Appointment)',
    contactEmail: 'counseling@nexora.edu',
  },
];

export const mockSampleRoute: NavigationRoute = {
  id: 'route_lib_to_sjt_g12',
  startPoint: 'Nexora Central Library (Main Entrance)',
  destination: 'Student Services Center (SJT Room G12)',
  etaMinutes: 4,
  distanceMeters: 280,
  floorChanges: ['Library Level 1 -> Ground Pathway -> SJT Level 0 (Ground)'],
  steps: [
    {
      instruction: 'Exit Central Library through the South Turnstile revolving doors.',
      distance: '30m',
      landmark: 'Library South Plaza Fountain',
    },
    {
      instruction: 'Take the covered glass skyway pedestrian walkway toward the Silver Jubilee Tower.',
      distance: '150m',
      landmark: 'Courtyard Sculpture',
    },
    {
      instruction: 'Enter SJT Main Atrium through sliding glass doors.',
      distance: '40m',
      landmark: 'SJT Digital Info Kiosk',
    },
    {
      instruction: 'Turn sharp right after the central security desks down Corridor A.',
      distance: '35m',
      landmark: 'Elevator Bank A',
    },
    {
      instruction: 'Arrive at Room G12 (Student Services Center) on your left.',
      distance: '25m',
      landmark: 'Signboard: Student Services & ID Desk',
    },
  ],
};

export const mockAdminMetric: AdminMetric = {
  totalKnowledgeItems: 1420,
  verifiedItems: 1294,
  pendingReview: 84,
  expiredItems: 42,
  activeUsersToday: 4812,
  systemHealth: 'Optimal',
};

export const mockVerificationQueue: VerificationItem[] = [
  {
    id: 'ver_01',
    title: 'Updated Policy: Overnight Lab Access Authorization 2026',
    type: 'procedure',
    submittedBy: 'Prof. Marcus Vance (Dean of Academic Affairs)',
    submittedAt: '2026-09-06T09:15:00Z',
    status: 'pending',
    notes: 'Requires approval of mandatory safety escort requirement after 11:00 PM.',
  },
  {
    id: 'ver_02',
    title: 'Relocation Notice: Faculty Office Hours - Dr. Elena Rostova',
    type: 'location',
    submittedBy: 'Dept. Coordinator Anita Roy',
    submittedAt: '2026-09-05T14:30:00Z',
    status: 'pending',
    notes: 'Room moved from SJT-314 to SJT-318 due to quantum instrumentation installation.',
  },
  {
    id: 'ver_03',
    title: 'New Service: Weekend Shuttle Route to Metro Station',
    type: 'service',
    submittedBy: 'Campus Transport Dept.',
    submittedAt: '2026-09-04T11:20:00Z',
    status: 'pending',
    notes: 'Hourly departures between 7:00 AM and 10:00 PM Saturdays & Sundays.',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann_01',
    title: 'Campus-wide Fiber Network Maintenance Tonight',
    message: 'Brief intermittent Wi-Fi disruption expected between 1:00 AM and 2:30 AM tonight.',
    priority: 'normal',
    category: 'IT Services',
    timestamp: '2026-09-06T12:00:00Z',
    department: 'IT Infrastructure',
  },
  {
    id: 'ann_02',
    title: 'Flu Vaccination Clinic Open at Health Pavilion',
    message: 'Free seasonal vaccinations available for all students and staff this Wednesday and Thursday.',
    priority: 'normal',
    category: 'Health',
    timestamp: '2026-09-05T09:00:00Z',
    department: 'Campus Health Center',
  },
];
