"""add_navigation_nodes_and_edges

Revision ID: 4a11fcd9f612
Revises: 5cc3849e0750
Create Date: 2026-09-06 22:54:10.972360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a11fcd9f612'
down_revision: Union[str, Sequence[str], None] = '5cc3849e0750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('node_type', sa.Enum('ENTRANCE', 'CORRIDOR', 'ROOM', 'STAIR', 'ELEVATOR', 'LANDMARK', 'INTERSECTION', 'EXIT', name='nodetype'), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('navigation_nodes', schema=None) as batch_op:
        batch_op.create_index('idx_nav_nodes_community_building_floor', ['community_id', 'building_id', 'floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_navigation_nodes_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_navigation_nodes_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_navigation_nodes_name'), ['name'], unique=False)

    op.create_table('navigation_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('community_id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('destination_node_id', sa.String(length=36), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('accessible', sa.Boolean(), nullable=False),
    sa.Column('stairs_required', sa.Boolean(), nullable=False),
    sa.Column('elevator_available', sa.Boolean(), nullable=False),
    sa.Column('bidirectional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_node_id'], ['navigation_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['navigation_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('navigation_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_navigation_edges_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_navigation_edges_destination_node_id'), ['destination_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_navigation_edges_source_node_id'), ['source_node_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_navigation_edges_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_navigation_edges_destination_node_id'))
        batch_op.drop_index(batch_op.f('ix_navigation_edges_community_id'))

    op.drop_table('navigation_edges')
    with op.batch_alter_table('navigation_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_navigation_nodes_name'))
        batch_op.drop_index(batch_op.f('ix_navigation_nodes_community_id'))
        batch_op.drop_index(batch_op.f('ix_navigation_nodes_building_id'))
        batch_op.drop_index('idx_nav_nodes_community_building_floor')

    op.drop_table('navigation_nodes')
    # ### end Alembic commands ###
